config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'applicants#index'

  resources :applicants
  

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base 
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController 
	def index 
		# @applicants = Applicant.all
		@sourcing_applicants = Applicant.where(stage: 'sourcing')
		@prescreen_applicants = Applicant.where(stage: 'pre_screen')
		@sampleteach_applicants = Applicant.where(stage: 'sample_teach')
		@debrief_applicants = Applicant.where(stage:'debrief')
		@offer_applicants = Applicant.where(stage: 'offer')

	end 

	def new 
		@applicant = Applicant.new 
	end 


	def create
    	@applicant = Applicant.new safe_applicant_params

    	if @applicant.save
      		redirect_to applicants_path
    	else
      		render 'new'
    	end
	end 

	def show 
		@applicant = Applicant.find params[:id]
	end 

	def edit 
		@applicant = Applicant.find params[:id]
	end 

	def update 
		@applicant = Applicant.find params[:id]

		if @applicant.update_attributes safe_applicant_params
			redirect_to applicants_path 
		else 
			render 'edit'
		end 
	end 

	private

    def safe_applicant_params
      params.require(:applicant).permit(:name, :date_applied, :years_experience, :current_employer, :teaching_experience, :website_URL, :stage)
    end


end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicatiionController 
	def create 
		is user_signed_in? 
			safe_comment = params.require(:comment).permit(:post).merge(story_id: params[:story_id])
			@comment = current_user.comments.create 
				safe_comment
				redirect_to@comment.story 
			else 
				redirect_to new_user_session_path, alert: "Only logged in users can comment."
			end 
		end 
	end 
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_applicant_helper.rb
module NewApplicantHelper
end

app/views/applicants/_form.html.erb
<%= form_for @applicant do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :years_experience %>
  <%= f.number_field :years_experience %>
  </div>
  <div>
  <%= f.label :current_employer %>
  <%= f.text_field :current_employer %>
  </div>
  
  <div>
  <%= f.label :teaching_experience %>
  <%= f.text_field :teaching_experience %> 
  </div>

  <div>
  <%= f.label :website_URL %>
  <%=f.text_field :website_URL %> 
  </div>

  <div>
  <%= f.label :stage %>
  <%=f.select :stage, options_for_select([['Sourcing', 'sourcing'], ['Prescreen', 'pre_screen'], ['Sample Teach', 'sample_teach'], ['Debrief', 'debrief'], ['Offer', 'offer']], @applicant.stage)%> 
  </div>

  <%= f.submit %>
<% end %>

app/views/applicants/edit.html.erb
<h1>Edit Applicant</h1>
<%= render 'form' %>

app/views/applicants/index.html.erb
<div class="welcome">
	<h1>Applicant Tracking System
	<%= link_to 'New Applicant', new_applicant_path, id: "new_btn" %>
	</h1>
</div>

	
	<div class="container">
  <div class="container-body">


    <div class="bucket">
      <h2>Prescreen</h2>
      <ul>
      	<% @sourcing_applicants.each do |applicant| %>
			<li><%= link_to applicant.name, applicant %></li>
		<% end %>
      </ul>
    </div>




     <div class="bucket">
      <h2>Prescreen</h2>
      <ul>
        <% @prescreen_applicants.each do |applicant| %>
			<li><%= link_to applicant.name, applicant %></li>
			<% end %>
      </ul>
    </div>




     <div class="bucket">
      <h2>Sample Teach</h2>
      <ul>
         <% @sampleteach_applicants.each do |applicant| %> 
         	<li><%= link_to applicant.name, applicant %></li>
         	<% end %> 
      </ul>
    </div>


     <div class="bucket">
      <h2>Debrief</h2>
      <ul>
        <% @debrief_applicants.each do |applicant| %> 
        	<li><%= link_to applicant.name, applicant %></li>
        	<% end %>
      </ul>
    </div>

     <div class="bucket">
      <h2>Offer</h2>
      <ul>
        <% @offer_applicants.each do |applicant| %> 
        	<li><%= link_to applicant.name, applicant %></li>
        	<% end %>
      </ul>
    </div>

  </div></div>

app/views/applicants/new.html.erb
<%= render 'form' %>

app/views/applicants/show.html.erb
<h1><%= @applicant.name %></h1>
<p>Years of Experience: <%= @applicant.years_experience %></p>
<p>Current Employer: <%= @applicant.current_employer %></p>
<p>Teaching Experience: <%= @applicant.teaching_experience %></p>
<p>LinkedIn: <%= @applicant.website_URL %></p>
<p>Stage: <%= @applicant.stage.humanize %></p>




<%= link_to "Edit", edit_applicant_path(@applicant) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApplicantTrackingSystem</title>
  <link rel="stylesheet" href="http://necolas.github.io/normalize.css/3.0.1/normalize.css">
  <link href='http://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header"><%= image_tag "ga.png", class: 'galogo' %></div>

<%= yield %>

</body>
</html>

app/views/new_applicant/index.html.erb
<%= form_for @applicant, url: {action: "create"} do |applicant_form| %>
  <%= applicant_form.text_field :name %>
<% end %>